### ISSUE TITLE
The timestamp on Readme.md is incorrect

### ISSUE THREAD

**Issue by s-i-d-d-i-s** [nileshsah/harwest-tool#1]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/YfpYCDZ/Capture.png" alt="Capture" border="0"></a>

The commit on readme has date 00:00:00 2000

If this is intended, maybe changing it to some user specified date would be better.
It's adding lot of years beside contribution graph

<img src="https://i.ibb.co/zH3rwLv/Capture.png" alt="Capture" border="0">

**Comment by nileshsah** [comment]
Hi, @s-i-d-d-i-s  Thanks for raising the issue. This is a very valid concern that I missed out on and should be addressed in priority. I've added a comment to the proposed fix in the PR. Would be great if you can take a look.
