### ISSUE TITLE
atcoder harwest for java submissions does not work

### ISSUE THREAD

**Issue by s-i-d-d-i-s** [nileshsah/harwest-tool#14]
Source : https://codeforces.com/blog/entry/85788?#comment-747260

Error Log says 

```python
ValueError: ("Please provide correct file extension for the language 'Java8 (OpenJDK 1.8.0)' in", 'C:\\Users\\bleh0\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\harwest\\lib\\resources\\language.json', 'file')
```

Possible Fix:

add the entry `"Java8 (OpenJDK 1.8.0)": "java"` in `language.json`

**Comment by nileshsah** [comment]
Thanks for raising the issue @s-i-d-d-i-s. The proposed entry has been added to the language.json config and is available in `Harwest 0.3.2` https://pypi.org/manage/project/harwest/release/0.3.2/
