### ISSUE TITLE
Support for Atcoder OJ

### ISSUE THREAD

**Issue by s-i-d-d-i-s** [nileshsah/harwest-tool#8]
Support for Atcoder can be easily added using Kenkooo API

Here's a example repo combining both Codeforces and Atcoder [Link](https://github.com/s-i-d-d-i-s/Atcoder-Test)

**Comment by nileshsah** [comment]
@s-i-d-d-i-s Thanks for the massive help! Support for AtCoder is now available in `harwest-0.3.0` https://pypi.org/project/harwest/0.3.0/ :)
